const KEY = 'hco.trials.v0.1';
const panel = document.querySelector('#labPanel');
const recent = document.querySelector('#recent');
const dataSummary = document.querySelector('#dataSummary');
let trials = JSON.parse(localStorage.getItem(KEY) || '[]');

function saveTrial(trial){trials.push(trial);localStorage.setItem(KEY,JSON.stringify(trials));renderData();}
function uid(){return crypto.randomUUID ? crypto.randomUUID() : 'trial-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function base(labId,params,response,metrics,confidence){return {id:uid(),labId,labVersion:'0.1.0',timestamp:new Date().toISOString(),parameters:params,response,metrics,confidence};}
function renderData(){dataSummary.textContent=`${trials.length} trials / この端末だけに保存`;recent.textContent=trials.length?JSON.stringify(trials.slice(-5).reverse(),null,2):'まだ記録はありません。';}
function show(html){panel.innerHTML=html;panel.classList.remove('hidden');panel.scrollIntoView({behavior:'smooth',block:'start'});}

function confidenceUI(){return `<div class="confidence"><label>確信度 <output id="confOut">50</output>%</label><br><input id="confidence" type="range" min="0" max="100" value="50"></div>`;}
function wireConfidence(){const r=document.querySelector('#confidence'),o=document.querySelector('#confOut');if(r)r.oninput=()=>o.value=r.value;}

function timeLab(){show(`<h2>Time Sense Lab</h2><p>スタート後、時計を見ずに「10秒」と感じた瞬間に止めてください。</p><div class="stage"><div><div id="timeMsg" class="big">Ready</div><button id="timeBtn">スタート</button>${confidenceUI()}</div></div>`);wireConfidence();let start=null;const btn=document.querySelector('#timeBtn');btn.onclick=()=>{if(!start){start=performance.now();document.querySelector('#timeMsg').textContent='…';btn.textContent='10秒だと思ったら押す';}else{const elapsed=performance.now()-start,err=elapsed-10000,conf=+document.querySelector('#confidence').value;saveTrial(base('time-sense',{targetMs:10000},{estimatedMs:Math.round(elapsed)},{signedErrorMs:Math.round(err),absoluteErrorMs:Math.round(Math.abs(err))},conf));document.querySelector('#timeMsg').textContent=(elapsed/1000).toFixed(2)+'秒';btn.textContent='もう一度';start=null;}}}

function quantityLab(){const count=10+Math.floor(Math.random()*31);show(`<h2>Quantity Sense Lab</h2><p>点は一瞬だけ表示されます。数えず、量の感覚で答えてください。</p><div class="stage" id="qStage"><button id="qStart">表示する</button></div>`);document.querySelector('#qStart').onclick=()=>{const stage=document.querySelector('#qStage');stage.innerHTML='<div class="dots" id="dots"></div>';const box=document.querySelector('#dots');for(let i=0;i<count;i++){const d=document.createElement('i');d.className='dot';d.style.left=(Math.random()*96)+'%';d.style.top=(Math.random()*94)+'%';box.appendChild(d)}setTimeout(()=>{stage.innerHTML=`<div><p>何個くらいありましたか？</p><input id="qAnswer" type="number" min="1" max="100" inputmode="numeric"> <button id="qSubmit">回答</button>${confidenceUI()}</div>`;wireConfidence();document.querySelector('#qSubmit').onclick=()=>{const ans=+document.querySelector('#qAnswer').value;if(!ans)return;const conf=+document.querySelector('#confidence').value;saveTrial(base('quantity-sense',{actualCount:count},{estimatedCount:ans},{signedError:ans-count,absoluteError:Math.abs(ans-count),relativeError:Math.abs(ans-count)/count},conf));stage.innerHTML=`<div><div class="big">${count}</div><p>あなたの回答 ${ans} / 誤差 ${Math.abs(ans-count)}</p><button id="qAgain">もう一度</button></div>`;document.querySelector('#qAgain').onclick=quantityLab;};},450);};}

function patternLab(){const patterns=[['○','△','○','△'],['1','2','4','1','2','4'],['■','■','□','■','■','□'],['A','B','C','B','A','B','C','B']];const p=patterns[Math.floor(Math.random()*patterns.length)];const seq=[];while(seq.length<7)seq.push(...p);const shown=seq.slice(0,6),correct=seq[6];const options=[...new Set([...p,'○','△','□','■','A','B','C','1','2','4'])].sort(()=>Math.random()-.5).slice(0,4);if(!options.includes(correct))options[0]=correct;options.sort(()=>Math.random()-.5);show(`<h2>Pattern Sense Lab</h2><p>規則を説明しなくて構いません。次に来ると思うものを選んでください。</p><div class="stage"><div><div class="big">${shown.join(' ')}</div><div class="choices">${options.map(x=>`<button data-answer="${x}">${x}</button>`).join('')}</div>${confidenceUI()}</div></div>`);wireConfidence();document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ans=b.dataset.answer,conf=+document.querySelector('#confidence').value,ok=ans===correct;saveTrial(base('pattern-sense',{shown,pattern:p},{answer:ans,correctAnswer:correct},{correct:ok?1:0},conf));document.querySelector('.stage').innerHTML=`<div><div class="big">${ok?'✓':'×'}</div><p>正解: ${correct}</p><button id="pAgain">もう一度</button></div>`;document.querySelector('#pAgain').onclick=patternLab;});}

document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>({time:timeLab,quantity:quantityLab,pattern:patternLab}[b.dataset.lab]()));
document.querySelector('#clearBtn').onclick=()=>{if(confirm('この端末のHCO記録をすべて削除しますか？')){trials=[];localStorage.removeItem(KEY);renderData();}};
document.querySelector('#exportBtn').onclick=()=>{const pack={schemaVersion:'0.1',generatedAt:new Date().toISOString(),privacy:{containsName:false,automaticUpload:false},summary:{trials:trials.length,labs:[...new Set(trials.map(t=>t.labId))]},trials};const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hco-research-pack-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);};
renderData();
