const KEY='hco.trials.v0.1';
const panel=document.querySelector('#labPanel');
const recent=document.querySelector('#recent');
const dataSummary=document.querySelector('#dataSummary');
const perceptionMap=document.querySelector('#perceptionMap');
let trials=JSON.parse(localStorage.getItem(KEY)||'[]');

const LAB_NAMES={
  'time-sense':'Time Sense','quantity-sense':'Quantity Sense','pattern-sense':'Pattern Sense',
  'reaction-time':'Reaction Time','flash-memory':'Flash Memory','change-detection':'Change Detection',
  'rhythm-sense':'Rhythm Sense','peripheral-vision':'Peripheral Vision','sequence-memory':'Sequence Memory',
  'mental-rotation':'Mental Rotation'
};

function uid(){return crypto.randomUUID?crypto.randomUUID():'trial-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function clamp(n,min,max){return Math.min(max,Math.max(min,n))}
function base(labId,params,response,metrics,confidence=50){return {id:uid(),labId,labVersion:'0.1.0',timestamp:new Date().toISOString(),parameters:params,response,metrics,confidence};}
function saveTrial(trial){trials.push(trial);localStorage.setItem(KEY,JSON.stringify(trials));renderData();}
function show(html){panel.innerHTML=html;panel.classList.remove('hidden');panel.scrollIntoView({behavior:'smooth',block:'start'});}
function confidenceUI(){return `<div class="confidence"><label>確信度 <output id="confOut">50</output>%</label><br><input id="confidence" type="range" min="0" max="100" value="50"></div>`;}
function wireConfidence(){const r=document.querySelector('#confidence'),o=document.querySelector('#confOut');if(r)r.oninput=()=>o.value=r.value;}
function conf(){return +(document.querySelector('#confidence')?.value||50)}
function resultView(title,main,detail,again){show(`<h2>${title}</h2><div class="stage"><div><div class="big">${main}</div><p>${detail}</p><button id="againBtn">もう一度</button></div></div>`);document.querySelector('#againBtn').onclick=again;}

function scoreTrial(t){
  const m=t.metrics||{};
  switch(t.labId){
    case 'time-sense': return clamp(100-(m.absoluteErrorMs||10000)/100,0,100);
    case 'quantity-sense': return clamp(100-(m.relativeError||1)*100,0,100);
    case 'pattern-sense': case 'change-detection': case 'peripheral-vision': case 'mental-rotation': return m.correct?100:0;
    case 'reaction-time': return clamp(100-((m.reactionMs||1000)-180)/8.2,0,100);
    case 'flash-memory': case 'sequence-memory': return clamp((m.accuracy||0)*100,0,100);
    case 'rhythm-sense': return clamp(100-(m.meanAbsoluteIntervalErrorMs||600)/6,0,100);
    default:return null;
  }
}
function renderMap(){
  perceptionMap.innerHTML=Object.entries(LAB_NAMES).map(([id,name])=>{
    const xs=trials.filter(t=>t.labId===id).map(scoreTrial).filter(Number.isFinite);
    const avg=xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
    return `<div class="mapItem"><div class="label"><span>${name}</span><span>${avg===null?'—':Math.round(avg)}</span></div><div class="bar"><i style="width:${avg===null?0:avg}%"></i></div><div class="muted">${xs.length} trial${xs.length===1?'':'s'}${avg===null?' / 未測定':' / 観測スコア'}</div></div>`;
  }).join('');
}
function renderData(){dataSummary.textContent=`${trials.length} trials / この端末だけに保存`;recent.textContent=trials.length?JSON.stringify(trials.slice(-5).reverse(),null,2):'まだ記録はありません。';renderMap();}

function timeLab(){show(`<h2>Time Sense Lab</h2><p>スタート後、時計を見ずに「10秒」と感じた瞬間に止めてください。</p><div class="stage"><div><div id="timeMsg" class="big">Ready</div><button id="timeBtn">スタート</button>${confidenceUI()}</div></div>`);wireConfidence();let start=null;const btn=document.querySelector('#timeBtn');btn.onclick=()=>{if(!start){start=performance.now();document.querySelector('#timeMsg').textContent='…';btn.textContent='10秒だと思ったら押す';}else{const elapsed=performance.now()-start,err=elapsed-10000,c=conf();saveTrial(base('time-sense',{targetMs:10000},{estimatedMs:Math.round(elapsed)},{signedErrorMs:Math.round(err),absoluteErrorMs:Math.round(Math.abs(err))},c));resultView('Time Sense Lab',(elapsed/1000).toFixed(2)+'秒',`誤差 ${(Math.abs(err)/1000).toFixed(2)}秒`,timeLab);}}}

function quantityLab(){const count=10+Math.floor(Math.random()*31);show(`<h2>Quantity Sense Lab</h2><p>点は一瞬だけ表示されます。数えず、量の感覚で答えてください。</p><div class="stage" id="qStage"><button id="qStart">表示する</button></div>`);document.querySelector('#qStart').onclick=()=>{const stage=document.querySelector('#qStage');stage.innerHTML='<div class="dots" id="dots"></div>';const box=document.querySelector('#dots');for(let i=0;i<count;i++){const d=document.createElement('i');d.className='dot';d.style.left=(Math.random()*96)+'%';d.style.top=(Math.random()*94)+'%';box.appendChild(d)}setTimeout(()=>{stage.innerHTML=`<div><p>何個くらいありましたか？</p><input id="qAnswer" type="number" min="1" max="100" inputmode="numeric"> <button id="qSubmit">回答</button>${confidenceUI()}</div>`;wireConfidence();document.querySelector('#qSubmit').onclick=()=>{const ans=+document.querySelector('#qAnswer').value;if(!ans)return;const c=conf();saveTrial(base('quantity-sense',{actualCount:count},{estimatedCount:ans},{signedError:ans-count,absoluteError:Math.abs(ans-count),relativeError:Math.abs(ans-count)/count},c));resultView('Quantity Sense Lab',count,`あなたの回答 ${ans} / 誤差 ${Math.abs(ans-count)}`,quantityLab);};},450);};}

function patternLab(){const patterns=[['○','△','○','△'],['1','2','4','1','2','4'],['■','■','□','■','■','□'],['A','B','C','B','A','B','C','B']];const p=patterns[Math.floor(Math.random()*patterns.length)];const seq=[];while(seq.length<7)seq.push(...p);const shown=seq.slice(0,6),correct=seq[6];let options=[...new Set([...p,'○','△','□','■','A','B','C','1','2','4'])].sort(()=>Math.random()-.5).slice(0,4);if(!options.includes(correct))options[0]=correct;options.sort(()=>Math.random()-.5);show(`<h2>Pattern Sense Lab</h2><p>規則を説明しなくて構いません。次に来ると思うものを選んでください。</p><div class="stage"><div><div class="big">${shown.join(' ')}</div><div class="choices">${options.map(x=>`<button data-answer="${x}">${x}</button>`).join('')}</div>${confidenceUI()}</div></div>`);wireConfidence();document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ans=b.dataset.answer,c=conf(),ok=ans===correct;saveTrial(base('pattern-sense',{shown,pattern:p},{answer:ans,correctAnswer:correct},{correct:ok?1:0},c));resultView('Pattern Sense Lab',ok?'✓':'×',`正解: ${correct}`,patternLab);});}

function reactionLab(){show(`<h2>Reaction Time Lab</h2><p>灰色の面が変わった瞬間に押してください。先に押した試行は記録しません。</p><div class="stage"><div id="signal" class="signal"><button id="reactStart">開始</button></div></div>`);let armed=false,start=0,timer;document.querySelector('#reactStart').onclick=()=>{const s=document.querySelector('#signal');s.innerHTML='待ってください…';timer=setTimeout(()=>{armed=true;start=performance.now();s.classList.add('go');s.textContent='今！';},1200+Math.random()*2200);s.onclick=()=>{if(!armed){clearTimeout(timer);s.textContent='早すぎます。もう一度。';setTimeout(reactionLab,700);return;}const ms=performance.now()-start;saveTrial(base('reaction-time',{randomDelay:true},{reactionMs:Math.round(ms)},{reactionMs:Math.round(ms)},50));resultView('Reaction Time Lab',Math.round(ms)+' ms','合図からクリックまで',reactionLab);};};}

function flashLab(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const target=Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('');show(`<h2>Flash Memory Lab</h2><p>短く表示される6文字を覚えてください。</p><div class="stage" id="flashStage"><button id="flashStart">表示する</button></div>`);document.querySelector('#flashStart').onclick=()=>{const s=document.querySelector('#flashStage');s.innerHTML=`<div class="big">${target}</div>`;setTimeout(()=>{s.innerHTML=`<div><p>覚えている文字列を入力</p><input id="flashAnswer" type="text" maxlength="6" autocomplete="off"> <button id="flashSubmit">回答</button>${confidenceUI()}</div>`;wireConfidence();document.querySelector('#flashSubmit').onclick=()=>{const ans=document.querySelector('#flashAnswer').value.toUpperCase().trim();let hits=0;for(let i=0;i<6;i++)if(ans[i]===target[i])hits++;saveTrial(base('flash-memory',{length:6,displayMs:700},{answer:ans,target},{accuracy:hits/6,positionHits:hits},conf()));resultView('Flash Memory Lab',`${hits}/6`,`正解 ${target}`,flashLab);};},700);};}

function makeGrid(){return Array.from({length:16},()=>Math.random()<.35?1:0)}
function changeLab(){const a=makeGrid();let b=[...a];const changed=Math.floor(Math.random()*16);b[changed]=b[changed]?0:1;const render=g=>`<div class="matrix">${g.map(v=>`<div class="cell ${v?'on':''}"></div>`).join('')}</div>`;show(`<h2>Change Detection Lab</h2><p>2つの配置の間で、変化した場所を見つけてください。</p><div class="stage" id="changeStage"><button id="changeStart">開始</button></div>`);document.querySelector('#changeStart').onclick=()=>{const s=document.querySelector('#changeStage');s.innerHTML=render(a);setTimeout(()=>{s.innerHTML='<div class="big">+</div>';setTimeout(()=>{s.innerHTML=render(b);setTimeout(()=>{s.innerHTML=`<div><p>変化したマスを選択</p><div class="matrix">${Array.from({length:16},(_,i)=>`<button class="cell" data-cell="${i}" aria-label="cell ${i+1}"></button>`).join('')}</div>${confidenceUI()}</div>`;wireConfidence();document.querySelectorAll('[data-cell]').forEach(btn=>btn.onclick=()=>{const ans=+btn.dataset.cell,ok=ans===changed;saveTrial(base('change-detection',{gridSize:16,changedIndex:changed},{selectedIndex:ans},{correct:ok?1:0},conf()));resultView('Change Detection Lab',ok?'✓':'×',`変化位置は ${changed+1} 番`,changeLab);});},650);},250);},650);};}

function rhythmLab(){const target=600;show(`<h2>Rhythm Sense Lab</h2><p>4回の提示テンポを画面の点滅で感じ、その後同じテンポで5回タップしてください。</p><div class="stage" id="rhythmStage"><button id="rhythmStart">開始</button></div>`);document.querySelector('#rhythmStart').onclick=()=>{const s=document.querySelector('#rhythmStage');let beat=0;s.innerHTML='<div class="big" id="beatDot">●</div>';const iv=setInterval(()=>{const d=document.querySelector('#beatDot');d.style.opacity=d.style.opacity==='0.2'?'1':'0.2';beat++;if(beat>=7){clearInterval(iv);setTimeout(()=>{s.innerHTML='<div><div id="tapPad" class="tapPad">ここを5回タップ</div><p id="tapCount">0 / 5</p></div>';const times=[];document.querySelector('#tapPad').onclick=()=>{times.push(performance.now());document.querySelector('#tapCount').textContent=`${times.length} / 5`;if(times.length===5){const ints=times.slice(1).map((t,i)=>t-times[i]);const mae=ints.reduce((sum,x)=>sum+Math.abs(x-target),0)/ints.length;saveTrial(base('rhythm-sense',{targetIntervalMs:target,taps:5},{intervalsMs:ints.map(Math.round)},{meanAbsoluteIntervalErrorMs:Math.round(mae)},50));resultView('Rhythm Sense Lab',`${Math.round(mae)} ms`,`平均テンポ誤差`,rhythmLab);}};},350);}},300);};}

function peripheralLab(){show(`<h2>Peripheral Vision Lab</h2><p>中央の「＋」を見続けてください。周辺に一瞬出る点がどの方向だったか答えます。</p><div class="stage" id="perStage"><button id="perStart">開始</button></div>`);document.querySelector('#perStart').onclick=()=>{const s=document.querySelector('#perStage');s.innerHTML='<div class="fixation" id="fix"><div class="cross">＋</div></div>';const dirs=[['左上',12,15],['右上',82,15],['左下',12,80],['右下',82,80]];const pick=Math.floor(Math.random()*4);setTimeout(()=>{const [name,x,y]=dirs[pick],d=document.createElement('i');d.className='peripheralDot';d.style.left=x+'%';d.style.top=y+'%';document.querySelector('#fix').appendChild(d);setTimeout(()=>{d.remove();setTimeout(()=>{s.innerHTML=`<div><p>どこに見えましたか？</p><div class="choices">${dirs.map((d,i)=>`<button data-dir="${i}">${d[0]}</button>`).join('')}</div>${confidenceUI()}</div>`;wireConfidence();document.querySelectorAll('[data-dir]').forEach(btn=>btn.onclick=()=>{const ans=+btn.dataset.dir,ok=ans===pick;saveTrial(base('peripheral-vision',{targetDirection:name,flashMs:120},{selectedDirection:dirs[ans][0]},{correct:ok?1:0},conf()));resultView('Peripheral Vision Lab',ok?'✓':'×',`正解: ${name}`,peripheralLab);});},200);},120);},900);};}

function sequenceLab(){const seq=Array.from({length:4},()=>Math.floor(Math.random()*9));show(`<h2>Sequence Memory Lab</h2><p>4回点灯する位置の順序を覚え、同じ順に押してください。</p><div class="stage" id="seqStage"><button id="seqStart">開始</button></div>`);document.querySelector('#seqStart').onclick=()=>{const s=document.querySelector('#seqStage');s.innerHTML=`<div class="seqGrid">${Array.from({length:9},(_,i)=>`<div class="seqCell" data-sq="${i}"></div>`).join('')}</div>`;let k=0;const play=()=>{if(k>=seq.length){setTimeout(()=>{const chosen=[];s.innerHTML=`<div><div class="seqGrid">${Array.from({length:9},(_,i)=>`<button class="seqCell" data-pick="${i}"></button>`).join('')}</div><p id="seqCount">0 / 4</p>${confidenceUI()}</div>`;wireConfidence();document.querySelectorAll('[data-pick]').forEach(btn=>btn.onclick=()=>{chosen.push(+btn.dataset.pick);document.querySelector('#seqCount').textContent=`${chosen.length} / 4`;if(chosen.length===4){const hits=chosen.filter((v,i)=>v===seq[i]).length;saveTrial(base('sequence-memory',{sequence:seq},{selectedSequence:chosen},{accuracy:hits/4,positionHits:hits},conf()));resultView('Sequence Memory Lab',`${hits}/4`,`位置と順番が一致した数`,sequenceLab);}});},350);return;}const el=document.querySelector(`[data-sq="${seq[k]}"]`);el.classList.add('active');setTimeout(()=>{el.classList.remove('active');k++;setTimeout(play,220);},420);};play();};}

function rotationLab(){const symbols=['L','F','R','P'];const symbol=symbols[Math.floor(Math.random()*symbols.length)],angle=[90,180,270][Math.floor(Math.random()*3)],mirrored=Math.random()<.5;show(`<h2>Mental Rotation Lab</h2><p>右の形は、左の形を回転しただけですか？ それとも鏡像ですか？</p><div class="stage"><div><div class="shapeWrap"><span class="shape">${symbol}</span><span class="shape" style="transform:rotate(${angle}deg) scaleX(${mirrored?-1:1})">${symbol}</span></div><div class="choices"><button data-rot="same">回転だけ</button><button data-rot="mirror">鏡像</button></div>${confidenceUI()}</div></div>`);wireConfidence();document.querySelectorAll('[data-rot]').forEach(btn=>btn.onclick=()=>{const ans=btn.dataset.rot,correct=mirrored?'mirror':'same',ok=ans===correct;saveTrial(base('mental-rotation',{symbol,angle,mirrored},{answer:ans,correctAnswer:correct},{correct:ok?1:0},conf()));resultView('Mental Rotation Lab',ok?'✓':'×',mirrored?'鏡像でした':'回転だけでした',rotationLab);});}

const handlers={time:timeLab,quantity:quantityLab,pattern:patternLab,reaction:reactionLab,flash:flashLab,change:changeLab,rhythm:rhythmLab,peripheral:peripheralLab,sequence:sequenceLab,rotation:rotationLab};
document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>handlers[b.dataset.lab]());
document.querySelector('#clearBtn').onclick=()=>{if(confirm('この端末のHCO記録をすべて削除しますか？')){trials=[];localStorage.removeItem(KEY);renderData();}};
document.querySelector('#exportBtn').onclick=()=>{const labSummary={};Object.keys(LAB_NAMES).forEach(id=>{const xs=trials.filter(t=>t.labId===id),scores=xs.map(scoreTrial).filter(Number.isFinite);labSummary[id]={trials:xs.length,observedScore:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null};});const pack={schemaVersion:'0.1',generatedAt:new Date().toISOString(),privacy:{containsName:false,automaticUpload:false,aiIntegration:false},interpretationRule:'Scores are deterministic observational summaries, not diagnoses or proof of latent abilities.',summary:{trials:trials.length,labs:[...new Set(trials.map(t=>t.labId))],labSummary},trials};const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hco-research-pack-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);};
renderData();
